FROM ubuntu:latest
LABEL org="One-Off Coder"
LABEL author="Diogo Santiago"
LABEL email="diogo.felipe.santiago@gmail.com"

ENV JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64
ENV HDFS_NAMENODE_USER=root
ENV HDFS_DATANODE_USER=root
ENV HDFS_SECONDARYNAMENODE_USER=root
ENV YARN_RESOURCEMANAGER_USER=root
ENV YARN_NODEMANAGER_USER=root
ENV YARN_PROXYSERVER_USER=root
ENV HADOOP_HOME=/usr/local/hadoop
ENV HADOOP_YARN_HOME=${HADOOP_HOME}
ENV HADOOP_CONF_DIR=${HADOOP_HOME}/etc/hadoop
ENV HADOOP_LOG_DIR=${HADOOP_YARN_HOME}/logs
ENV HADOOP_IDENT_STRING=root
ENV HADOOP_MAPRED_IDENT_STRING=root
ENV HADOOP_MAPRED_HOME=${HADOOP_HOME}
ENV PATH=${PATH}:${HADOOP_HOME}/bin
# ENV NOTEBOOK_PASSWORD=""

# setup ubuntu
RUN apt-get update -y \
    && apt-get upgrade -y \
    && apt-get -y install openjdk-8-jdk wget openssh-server sshpass supervisor \
    && apt-get -y install nano net-tools lynx \
    && apt-get clean

RUN addgroup hadoop 

RUN adduser --ingroup hadoop hdfs

# setup ssh
RUN ssh-keygen -t rsa -P "" -f ~/.ssh/id_rsa \
    && cat ~/.ssh/id_rsa.pub >> /root/.ssh/authorized_keys \
    && chmod 0600 ~/.ssh/authorized_keys

COPY configs/.ssh/config /root/.ssh/config

# setup hadoop
RUN wget -q https://dlcdn.apache.org/hadoop/common/hadoop-3.3.3/hadoop-3.3.3.tar.gz -O /tmp/hadoop-3.3.3.tar.gz \
    && tar -xzf /tmp/hadoop-3.3.3.tar.gz -C /usr/local/ \
    && ln -s /usr/local/hadoop-3.3.3 /usr/local/hadoop \
    && rm -fr /usr/local/hadoop/etc/hadoop/* 

COPY configs/hadoop/*.xml configs/hadoop/*.sh $HADOOP_CONF_DIR

RUN mkdir -p /data/nn/ /data/dn/ && chown hdfs:hadoop -R /data

RUN groupadd supergroup && usermod -a -G supergroup root

# RUN $HADOOP_HOME/bin/hdfs namenode -format

COPY bootstrap.sh /etc/bootstrap.sh

RUN chmod +x /etc/bootstrap.sh

CMD ["/etc/bootstrap.sh", "-d"]